
// Code generated by stanc v2.29.2
#include <stan/model/model_header.hpp>
namespace HN_series_fromDRT_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 50> locations_array__ = 
{" (found before start of program)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 36, column 1 to column 29)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 37, column 1 to column 60)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 39, column 1 to column 37)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 40, column 1 to column 36)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 43, column 1 to column 31)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 44, column 1 to column 31)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 48, column 1 to column 49)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 51, column 1 to column 65)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 52, column 1 to column 65)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 53, column 1 to column 68)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 54, column 1 to column 40)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 58, column 2 to column 33)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 60, column 3 to column 28)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 61, column 3 to column 66)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 59, column 16 to line 62, column 3)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 59, column 2 to line 62, column 3)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 57, column 15 to line 63, column 2)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 57, column 1 to line 63, column 2)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 67, column 1 to column 25)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 70, column 1 to column 40)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 71, column 1 to column 32)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 72, column 1 to column 32)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 14, column 1 to column 16)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 15, column 1 to column 16)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 18, column 8 to column 9)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 18, column 1 to column 15)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 19, column 8 to column 9)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 19, column 1 to column 17)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 22, column 1 to column 26)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 23, column 1 to column 26)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 26, column 1 to column 26)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 27, column 1 to column 33)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 28, column 1 to column 33)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 31, column 1 to column 37)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 32, column 1 to column 37)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 36, column 17 to column 18)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 37, column 48 to column 49)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 39, column 25 to column 26)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 40, column 25 to column 26)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 48, column 17 to column 18)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 53, column 17 to column 18)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 54, column 8 to column 9)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 3, column 2 to column 66)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 2, column 34 to line 4, column 2)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 6, column 5 to column 36)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 7, column 5 to column 59)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 8, column 5 to column 103)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 9, column 5 to column 24)",
 " (in 'C:/Users/jdh10/ONEDRI~1/python/projects/HYBRID~1/hybdrt/STAN_M~1/HN_series_fromDRT.stan', line 5, column 46 to line 10, column 2)"};

struct gamma_hn_functor__ {
  template <typename T0__, typename T1__, typename T2__,
            stan::require_stan_scalar_t<T0__>* = nullptr,
            stan::require_stan_scalar_t<T1__>* = nullptr,
            stan::require_stan_scalar_t<T2__>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__>
  operator()(const T0__& t, const T1__& alpha, const T2__& beta,
             std::ostream* pstream__) const;
};
struct theta_hn_functor__ {
  template <typename T0__, typename T1__,
            stan::require_stan_scalar_t<T0__>* = nullptr,
            stan::require_stan_scalar_t<T1__>* = nullptr>
  stan::promote_args_t<T0__, T1__>
  operator()(const T0__& t, const T1__& beta, std::ostream* pstream__) const;
};

template <typename T0__, typename T1__,
          stan::require_stan_scalar_t<T0__>* = nullptr,
          stan::require_stan_scalar_t<T1__>* = nullptr>
  stan::promote_args_t<T0__, T1__>
  theta_hn(const T0__& t, const T1__& beta, std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      current_statement__ = 43;
      return stan::math::atan2(stan::math::sin((stan::math::pi() * beta)),
               (stan::math::pow(t, beta) +
                 stan::math::cos((stan::math::pi() * beta))));
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__, typename T2__,
          stan::require_stan_scalar_t<T0__>* = nullptr,
          stan::require_stan_scalar_t<T1__>* = nullptr,
          stan::require_stan_scalar_t<T2__>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__>
  gamma_hn(const T0__& t, const T1__& alpha, const T2__& beta,
           std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ theta = DUMMY_VAR__;
      current_statement__ = 45;
      theta = theta_hn(t, beta, pstream__);
      local_scalar_t__ nume = DUMMY_VAR__;
      current_statement__ = 46;
      nume = (stan::math::pow(t, (beta * alpha)) *
               stan::math::sin((alpha * theta)));
      local_scalar_t__ deno = DUMMY_VAR__;
      current_statement__ = 47;
      deno = ((2 * stan::math::pi()) *
               stan::math::pow(
                 ((1 +
                    ((2 * stan::math::cos((stan::math::pi() * beta))) *
                      stan::math::pow(t, beta))) +
                   stan::math::pow(t, (2 * beta))), (alpha / 2)));
      current_statement__ = 48;
      return (nume / deno);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__, typename T2__,
          stan::require_stan_scalar_t<T0__>*,
          stan::require_stan_scalar_t<T1__>*,
          stan::require_stan_scalar_t<T2__>*>
stan::promote_args_t<T0__, T1__, T2__>
gamma_hn_functor__::operator()(const T0__& t, const T1__& alpha,
                               const T2__& beta, std::ostream* pstream__) 
const
{
  return gamma_hn(t, alpha, beta, pstream__);
}

template <typename T0__, typename T1__, stan::require_stan_scalar_t<T0__>*,
          stan::require_stan_scalar_t<T1__>*>
stan::promote_args_t<T0__, T1__>
theta_hn_functor__::operator()(const T0__& t, const T1__& beta,
                               std::ostream* pstream__)  const
{
  return theta_hn(t, beta, pstream__);
}


class HN_series_fromDRT_model final : public model_base_crtp<HN_series_fromDRT_model> {

 private:
  int M;
  int K;
  Eigen::Matrix<double, -1, 1> tau__;
  Eigen::Matrix<double, -1, 1> gamma__;
  double min_tau_hn;
  double max_tau_hn;
  double r_hn_scale;
  double sigma_alpha_scale;
  double sigma_const_scale;
  double min_lntau_hn;
  double max_lntau_hn; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> tau{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> gamma{nullptr, 0};
 
 public:
  ~HN_series_fromDRT_model() { }
  
  inline std::string model_name() const final { return "HN_series_fromDRT_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.29.2", "stancflags = "};
  }
  
  
  HN_series_fromDRT_model(stan::io::var_context& context__,
                          unsigned int random_seed__ = 0,
                          std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "HN_series_fromDRT_model_namespace::HN_series_fromDRT_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 23;
      context__.validate_dims("data initialization","M","int",
           std::vector<size_t>{});
      M = std::numeric_limits<int>::min();
      
      
      current_statement__ = 23;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 23;
      stan::math::check_greater_or_equal(function__, "M", M, 0);
      current_statement__ = 24;
      context__.validate_dims("data initialization","K","int",
           std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      
      
      current_statement__ = 24;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 24;
      stan::math::check_greater_or_equal(function__, "K", K, 0);
      current_statement__ = 25;
      stan::math::validate_non_negative_index("tau", "M", M);
      current_statement__ = 26;
      context__.validate_dims("data initialization","tau","double",
           std::vector<size_t>{static_cast<size_t>(M)});
      tau__ = 
        Eigen::Matrix<double, -1, 1>::Constant(M,
          std::numeric_limits<double>::quiet_NaN());
      new (&tau) Eigen::Map<Eigen::Matrix<double, -1, 1>>(tau__.data(), M);
      
      {
        std::vector<local_scalar_t__> tau_flat__;
        current_statement__ = 26;
        tau_flat__ = context__.vals_r("tau");
        current_statement__ = 26;
        pos__ = 1;
        current_statement__ = 26;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 26;
          stan::model::assign(tau, tau_flat__[(pos__ - 1)],
            "assigning variable tau", stan::model::index_uni(sym1__));
          current_statement__ = 26;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 27;
      stan::math::validate_non_negative_index("gamma", "M", M);
      current_statement__ = 28;
      context__.validate_dims("data initialization","gamma","double",
           std::vector<size_t>{static_cast<size_t>(M)});
      gamma__ = 
        Eigen::Matrix<double, -1, 1>::Constant(M,
          std::numeric_limits<double>::quiet_NaN());
      new (&gamma) Eigen::Map<Eigen::Matrix<double, -1, 1>>(gamma__.data(), M);
        
      
      {
        std::vector<local_scalar_t__> gamma_flat__;
        current_statement__ = 28;
        gamma_flat__ = context__.vals_r("gamma");
        current_statement__ = 28;
        pos__ = 1;
        current_statement__ = 28;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 28;
          stan::model::assign(gamma, gamma_flat__[(pos__ - 1)],
            "assigning variable gamma", stan::model::index_uni(sym1__));
          current_statement__ = 28;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 29;
      context__.validate_dims("data initialization","min_tau_hn","double",
           std::vector<size_t>{});
      min_tau_hn = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 29;
      min_tau_hn = context__.vals_r("min_tau_hn")[(1 - 1)];
      current_statement__ = 29;
      stan::math::check_greater_or_equal(function__, "min_tau_hn",
                                            min_tau_hn, 0);
      current_statement__ = 30;
      context__.validate_dims("data initialization","max_tau_hn","double",
           std::vector<size_t>{});
      max_tau_hn = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 30;
      max_tau_hn = context__.vals_r("max_tau_hn")[(1 - 1)];
      current_statement__ = 30;
      stan::math::check_greater_or_equal(function__, "max_tau_hn",
                                            max_tau_hn, 0);
      current_statement__ = 31;
      context__.validate_dims("data initialization","r_hn_scale","double",
           std::vector<size_t>{});
      r_hn_scale = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 31;
      r_hn_scale = context__.vals_r("r_hn_scale")[(1 - 1)];
      current_statement__ = 31;
      stan::math::check_greater_or_equal(function__, "r_hn_scale",
                                            r_hn_scale, 0);
      current_statement__ = 32;
      context__.validate_dims("data initialization","sigma_alpha_scale",
          "double", std::vector<size_t>{});
      sigma_alpha_scale = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 32;
      sigma_alpha_scale = context__.vals_r("sigma_alpha_scale")[(1 - 1)];
      current_statement__ = 32;
      stan::math::check_greater_or_equal(function__, "sigma_alpha_scale",
                                            sigma_alpha_scale, 0);
      current_statement__ = 33;
      context__.validate_dims("data initialization","sigma_const_scale",
          "double", std::vector<size_t>{});
      sigma_const_scale = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 33;
      sigma_const_scale = context__.vals_r("sigma_const_scale")[(1 - 1)];
      current_statement__ = 33;
      stan::math::check_greater_or_equal(function__, "sigma_const_scale",
                                            sigma_const_scale, 0);
      current_statement__ = 34;
      min_lntau_hn = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 34;
      min_lntau_hn = stan::math::log(min_tau_hn);
      current_statement__ = 35;
      max_lntau_hn = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 35;
      max_lntau_hn = stan::math::log(max_tau_hn);
      current_statement__ = 36;
      stan::math::validate_non_negative_index("r_hn_raw", "K", K);
      current_statement__ = 37;
      stan::math::validate_non_negative_index("lntau_hn", "K", K);
      current_statement__ = 38;
      stan::math::validate_non_negative_index("alpha_hn", "K", K);
      current_statement__ = 39;
      stan::math::validate_non_negative_index("beta_hn", "K", K);
      current_statement__ = 40;
      stan::math::validate_non_negative_index("r_hn", "K", K);
      current_statement__ = 41;
      stan::math::validate_non_negative_index("sigma_gamma", "M", M);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("gamma_hat", "M", M);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = K + K + K + K + 1 + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "HN_series_fromDRT_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<local_scalar_t__, -1, 1> r_hn_raw =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      r_hn_raw = in__.template read_constrain_lb<
                   Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(0,
                   lp__, K);
      Eigen::Matrix<local_scalar_t__, -1, 1> lntau_hn =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 2;
      lntau_hn = in__.template read_constrain_lub<
                   Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(
                   min_lntau_hn, max_lntau_hn, lp__, K);
      Eigen::Matrix<local_scalar_t__, -1, 1> alpha_hn =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 3;
      alpha_hn = in__.template read_constrain_lub<
                   Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(0, 1,
                   lp__, K);
      Eigen::Matrix<local_scalar_t__, -1, 1> beta_hn =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 4;
      beta_hn = in__.template read_constrain_lub<
                  Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(0, 1,
                  lp__, K);
      local_scalar_t__ sigma_alpha_raw = DUMMY_VAR__;
      current_statement__ = 5;
      sigma_alpha_raw = in__.template read_constrain_lb<local_scalar_t__, 
                          jacobian__>(0, lp__);
      local_scalar_t__ sigma_const_raw = DUMMY_VAR__;
      current_statement__ = 6;
      sigma_const_raw = in__.template read_constrain_lb<local_scalar_t__, 
                          jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__, -1, 1> r_hn =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(r_hn, stan::math::multiply(r_hn_raw, r_hn_scale),
        "assigning variable r_hn");
      local_scalar_t__ sigma_alpha = DUMMY_VAR__;
      current_statement__ = 8;
      sigma_alpha = (sigma_alpha_raw * sigma_alpha_scale);
      local_scalar_t__ sigma_const = DUMMY_VAR__;
      current_statement__ = 9;
      sigma_const = (sigma_const_raw * sigma_const_scale);
      Eigen::Matrix<local_scalar_t__, -1, 1> sigma_gamma =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(M, DUMMY_VAR__);
      current_statement__ = 10;
      stan::model::assign(sigma_gamma,
        stan::math::add(stan::math::multiply(sigma_alpha, gamma),
          sigma_const), "assigning variable sigma_gamma");
      Eigen::Matrix<local_scalar_t__, -1, 1> gamma_hat =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(M, DUMMY_VAR__);
      current_statement__ = 11;
      stan::model::assign(gamma_hat, stan::math::rep_vector(0, M),
        "assigning variable gamma_hat");
      current_statement__ = 18;
      for (int k = 1; k <= K; ++k) {
        local_scalar_t__ tau_hn = DUMMY_VAR__;
        current_statement__ = 12;
        tau_hn = stan::math::exp(
                   stan::model::rvalue(lntau_hn, "lntau_hn",
                     stan::model::index_uni(k)));
        current_statement__ = 16;
        for (int m = 1; m <= M; ++m) {
          local_scalar_t__ t = DUMMY_VAR__;
          current_statement__ = 13;
          t = (stan::model::rvalue(tau, "tau", stan::model::index_uni(m)) /
                tau_hn);
          current_statement__ = 14;
          stan::model::assign(gamma_hat,
            (stan::model::rvalue(gamma_hat, "gamma_hat",
               stan::model::index_uni(m)) +
              (stan::model::rvalue(r_hn, "r_hn", stan::model::index_uni(k)) *
                gamma_hn(t,
                  stan::model::rvalue(alpha_hn, "alpha_hn",
                    stan::model::index_uni(k)),
                  stan::model::rvalue(beta_hn, "beta_hn",
                    stan::model::index_uni(k)), pstream__))),
            "assigning variable gamma_hat", stan::model::index_uni(m));
        }
      }
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "r_hn", r_hn, 0);
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "sigma_alpha",
                                            sigma_alpha, 0);
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "sigma_const",
                                            sigma_const, 0);
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "sigma_gamma",
                                            sigma_gamma, 0);
      {
        current_statement__ = 19;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(r_hn_raw));
        current_statement__ = 20;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(gamma, gamma_hat, sigma_gamma));
        current_statement__ = 21;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(sigma_alpha_raw));
        current_statement__ = 22;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(sigma_const_raw));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "HN_series_fromDRT_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<double, -1, 1> r_hn_raw =
         Eigen::Matrix<double, -1, 1>::Constant(K,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      r_hn_raw = in__.template read_constrain_lb<
                   Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(0,
                   lp__, K);
      Eigen::Matrix<double, -1, 1> lntau_hn =
         Eigen::Matrix<double, -1, 1>::Constant(K,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      lntau_hn = in__.template read_constrain_lub<
                   Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(
                   min_lntau_hn, max_lntau_hn, lp__, K);
      Eigen::Matrix<double, -1, 1> alpha_hn =
         Eigen::Matrix<double, -1, 1>::Constant(K,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      alpha_hn = in__.template read_constrain_lub<
                   Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(0, 1,
                   lp__, K);
      Eigen::Matrix<double, -1, 1> beta_hn =
         Eigen::Matrix<double, -1, 1>::Constant(K,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      beta_hn = in__.template read_constrain_lub<
                  Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(0, 1,
                  lp__, K);
      double sigma_alpha_raw = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      sigma_alpha_raw = in__.template read_constrain_lb<local_scalar_t__, 
                          jacobian__>(0, lp__);
      double sigma_const_raw = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      sigma_const_raw = in__.template read_constrain_lb<local_scalar_t__, 
                          jacobian__>(0, lp__);
      Eigen::Matrix<double, -1, 1> r_hn =
         Eigen::Matrix<double, -1, 1>::Constant(K,
           std::numeric_limits<double>::quiet_NaN());
      double sigma_alpha = std::numeric_limits<double>::quiet_NaN();
      double sigma_const = std::numeric_limits<double>::quiet_NaN();
      Eigen::Matrix<double, -1, 1> sigma_gamma =
         Eigen::Matrix<double, -1, 1>::Constant(M,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> gamma_hat =
         Eigen::Matrix<double, -1, 1>::Constant(M,
           std::numeric_limits<double>::quiet_NaN());
      out__.write(r_hn_raw);
      out__.write(lntau_hn);
      out__.write(alpha_hn);
      out__.write(beta_hn);
      out__.write(sigma_alpha_raw);
      out__.write(sigma_const_raw);
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 7;
      stan::model::assign(r_hn, stan::math::multiply(r_hn_raw, r_hn_scale),
        "assigning variable r_hn");
      current_statement__ = 8;
      sigma_alpha = (sigma_alpha_raw * sigma_alpha_scale);
      current_statement__ = 9;
      sigma_const = (sigma_const_raw * sigma_const_scale);
      current_statement__ = 10;
      stan::model::assign(sigma_gamma,
        stan::math::add(stan::math::multiply(sigma_alpha, gamma),
          sigma_const), "assigning variable sigma_gamma");
      current_statement__ = 11;
      stan::model::assign(gamma_hat, stan::math::rep_vector(0, M),
        "assigning variable gamma_hat");
      current_statement__ = 18;
      for (int k = 1; k <= K; ++k) {
        double tau_hn = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 12;
        tau_hn = stan::math::exp(
                   stan::model::rvalue(lntau_hn, "lntau_hn",
                     stan::model::index_uni(k)));
        current_statement__ = 16;
        for (int m = 1; m <= M; ++m) {
          double t = std::numeric_limits<double>::quiet_NaN();
          current_statement__ = 13;
          t = (stan::model::rvalue(tau, "tau", stan::model::index_uni(m)) /
                tau_hn);
          current_statement__ = 14;
          stan::model::assign(gamma_hat,
            (stan::model::rvalue(gamma_hat, "gamma_hat",
               stan::model::index_uni(m)) +
              (stan::model::rvalue(r_hn, "r_hn", stan::model::index_uni(k)) *
                gamma_hn(t,
                  stan::model::rvalue(alpha_hn, "alpha_hn",
                    stan::model::index_uni(k)),
                  stan::model::rvalue(beta_hn, "beta_hn",
                    stan::model::index_uni(k)), pstream__))),
            "assigning variable gamma_hat", stan::model::index_uni(m));
        }
      }
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "r_hn", r_hn, 0);
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "sigma_alpha",
                                            sigma_alpha, 0);
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "sigma_const",
                                            sigma_const, 0);
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "sigma_gamma",
                                            sigma_gamma, 0);
      if (emit_transformed_parameters__) {
        out__.write(r_hn);
        out__.write(sigma_alpha);
        out__.write(sigma_const);
        out__.write(sigma_gamma);
        out__.write(gamma_hat);
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__, -1, 1> r_hn_raw =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(K, DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        stan::model::assign(r_hn_raw, in__.read<local_scalar_t__>(),
          "assigning variable r_hn_raw", stan::model::index_uni(sym1__));
      }
      out__.write_free_lb(0, r_hn_raw);
      Eigen::Matrix<local_scalar_t__, -1, 1> lntau_hn =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(K, DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        stan::model::assign(lntau_hn, in__.read<local_scalar_t__>(),
          "assigning variable lntau_hn", stan::model::index_uni(sym1__));
      }
      out__.write_free_lub(min_lntau_hn, max_lntau_hn, lntau_hn);
      Eigen::Matrix<local_scalar_t__, -1, 1> alpha_hn =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(K, DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        stan::model::assign(alpha_hn, in__.read<local_scalar_t__>(),
          "assigning variable alpha_hn", stan::model::index_uni(sym1__));
      }
      out__.write_free_lub(0, 1, alpha_hn);
      Eigen::Matrix<local_scalar_t__, -1, 1> beta_hn =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(K, DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        stan::model::assign(beta_hn, in__.read<local_scalar_t__>(),
          "assigning variable beta_hn", stan::model::index_uni(sym1__));
      }
      out__.write_free_lub(0, 1, beta_hn);
      local_scalar_t__ sigma_alpha_raw = DUMMY_VAR__;
      sigma_alpha_raw = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_alpha_raw);
      local_scalar_t__ sigma_const_raw = DUMMY_VAR__;
      sigma_const_raw = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_const_raw);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"r_hn_raw", "lntau_hn", "alpha_hn",
      "beta_hn", "sigma_alpha_raw", "sigma_const_raw", "r_hn", "sigma_alpha",
      "sigma_const", "sigma_gamma", "gamma_hat"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{
                                                                   static_cast<size_t>(K)
                                                                   },
      std::vector<size_t>{static_cast<size_t>(K)},
      std::vector<size_t>{static_cast<size_t>(K)},
      std::vector<size_t>{static_cast<size_t>(K)}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{static_cast<size_t>(K)},
      std::vector<size_t>{}, std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(M)},
      std::vector<size_t>{static_cast<size_t>(M)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "r_hn_raw" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "lntau_hn" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "alpha_hn" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta_hn" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "sigma_alpha_raw");
    param_names__.emplace_back(std::string() + "sigma_const_raw");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "r_hn" + '.' + std::to_string(sym1__));
        } 
      }
      param_names__.emplace_back(std::string() + "sigma_alpha");
      param_names__.emplace_back(std::string() + "sigma_const");
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "sigma_gamma" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "gamma_hat" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "r_hn_raw" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "lntau_hn" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "alpha_hn" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta_hn" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "sigma_alpha_raw");
    param_names__.emplace_back(std::string() + "sigma_const_raw");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "r_hn" + '.' + std::to_string(sym1__));
        } 
      }
      param_names__.emplace_back(std::string() + "sigma_alpha");
      param_names__.emplace_back(std::string() + "sigma_const");
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "sigma_gamma" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "gamma_hat" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"r_hn_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"lntau_hn\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"alpha_hn\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"beta_hn\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"sigma_alpha_raw\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_const_raw\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"r_hn\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"sigma_alpha\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"sigma_const\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"sigma_gamma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"},{\"name\":\"gamma_hat\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"r_hn_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"lntau_hn\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"alpha_hn\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"beta_hn\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"sigma_alpha_raw\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_const_raw\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"r_hn\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"sigma_alpha\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"sigma_const\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"sigma_gamma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"},{\"name\":\"gamma_hat\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (((((K + K) + K) + K) + 1) + 1);
      const size_t num_transformed = 
  ((((K + 1) + 1) + M) + M);
      const size_t num_gen_quantities = 0;
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (((((K + K) + K) + K) + 1) + 1);
      const size_t num_transformed = 
  ((((K + 1) + 1) + M) + M);
      const size_t num_gen_quantities = 0;
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 6> names__{"r_hn_raw", "lntau_hn",
      "alpha_hn", "beta_hn", "sigma_alpha_raw", "sigma_const_raw"};
      const std::array<Eigen::Index, 6> constrain_param_sizes__{K, K, 
       K, K, 1, 1};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
     }; } 
using stan_model = HN_series_fromDRT_model_namespace::HN_series_fromDRT_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return HN_series_fromDRT_model_namespace::profiles__;
}

#endif


